import pickle

SUBTYPES_TO_REMOVE = [
 'WINTERGARTEN',
 'OUTDOOR_VOID',
 'MEETING_ROOM',
 'SALESROOM',
 'OPEN_PLAN_OFFICE',
 'PRAM',
 'ARCHIVE',
 'WAITING_ROOM',
 'OIL_TANK',
 'TRANSPORT_SHAFT',
 'AIR',
 'RECEPTION_ROOM',
 'FACTORY_ROOM',
 'WATER_SUPPLY',
 'COUNTER_ROOM',
 'TEACHING_ROOM',
 'BREAK_ROOM',
 'LOGISTICS',
 'RADATION_THERAPY',
 'WORKSHOP',
 'DEDICATED_MEDICAL_ROOM',
 'GAS',
 'PHYSIO_AND_REHABILITATION',
 'ARCADE']

SUBTYPE_MAPPING = {
    'ROOM': 'Bedroom',
    'BEDROOM': 'Bedroom',
    'KITCHEN': 'Kitchen-Dining',
    'DINING': 'Kitchen-Dining',
    'KITCHEN_DINING': 'Kitchen-Dining',
    'LIVING_ROOM': 'Living-Room',
    'LIVING_DINING': 'Living-Room',
    'RECEPTION_ROOM': 'Living-Room',
    'BATHROOM': 'Bathroom',
    'TOILET': 'Bathroom',
    'SHOWER': 'Bathroom',
    'BATHTUB': 'Bathroom',
    'CORRIDOR': 'Corridor',
    'CORRIDORS_AND_HALLS': 'Corridor',
    'LOBBY': 'Corridor',
    'OFFICE': 'Office',
    'OFFICE_SPACE': 'Office',
    'OPEN_PLAN_OFFICE': 'Office',
    'STAIRS': 'Stairs-Ramp',
    'STAIRCASE': 'Stairs-Ramp',
    'RAMP': 'Stairs-Ramp',
    'BASEMENT': 'Basement',
    'BASEMENT_COMPARTMENT': 'Basement',
    'COLD_STORAGE': 'Basement',
    'GARAGE': 'Garage',
    'BIKE_STORAGE': 'Garage',
    'PRAM_AND_BIKE_STORAGE_ROOM': 'Garage',
    'CARPARK': 'Garage',
    'WORKSHOP': 'Workshop',
    'FACTORY_ROOM': 'Workshop',
    'BALCONY': 'Outdoor-Area',
    'GARDEN': 'Outdoor-Area',
    'TERRACE': 'Outdoor-Area',
    'PATIO': 'Outdoor-Area',
    'OUTDOOR_VOID': 'Outdoor-Area',
    'WAREHOUSE': 'Warehouse-Logistics',
    'LOGISTICS': 'Warehouse-Logistics',
    'ARCHIVE': 'Archive-Records',
    'RECORDS': 'Archive-Records',
    'MEETING_ROOM': 'Meeting-Salesroom',
    'SALESROOM': 'Meeting-Salesroom',
    'SHOWROOM': 'Meeting-Salesroom'
}

ZONING_MAPPING = {
    'ROOM': 'Zone1',
    'BEDROOM': 'Zone1',
    'KITCHEN': 'Zone2',
    'DINING': 'Zone2',
    'KITCHEN_DINING': 'Zone2',
    'LIVING_ROOM': 'Zone2',
    'LIVING_DINING': 'Zone2',
    'RECEPTION_ROOM': 'Remaining',
    'BATHROOM': 'Zone3',
    'TOILET': 'Zone3',
    'SHOWER': 'Zone3',
    'BATHTUB': 'Zone3',
    'CORRIDOR': 'Zone2',
    'CORRIDORS_AND_HALLS': 'Zone2',
    'LOBBY': 'Remaining',
    'OFFICE': 'Remaining',
    'OFFICE_SPACE': 'Remaining',
    'OPEN_PLAN_OFFICE': 'Remaining',
    'STAIRS': 'Zone3',
    'STAIRCASE': 'Zone3',
    'RAMP': 'Remaining',
    'BASEMENT': 'Remaining',
    'BASEMENT_COMPARTMENT': 'Remaining',
    'COLD_STORAGE': 'Remaining',
    'GARAGE': 'Remaining',
    'BIKE_STORAGE': 'Remaining',
    'PRAM_AND_BIKE_STORAGE_ROOM': 'Remaining',
    'CARPARK': 'Remaining',
    'WORKSHOP': 'Remaining',
    'FACTORY_ROOM': 'Remaining',
    'BALCONY': 'Balcony',
    'GARDEN': 'Remaining',
    'TERRACE': 'Remaining',
    'PATIO': 'Remaining',
    'OUTDOOR_VOID': 'Remaining',
    'WAREHOUSE': 'Remaining',
    'LOGISTICS': 'Remaining',
    'ARCHIVE': 'Remaining',
    'RECORDS': 'Remaining',
    'MEETING_ROOM': 'Remaining',
    'SALESROOM': 'Remaining',
    'SHOWROOM': 'Remaining'
}


def save_pickle(object, filename):
    with open(filename, 'wb') as f:
        pickle.dump(object, f)
    f.close()


def load_pickle(filename):
    with open(filename, 'rb') as f:
        object = pickle.load(f)
        f.close()
    return object